# Nginx
nginx: 
 build: .
 dockerfile: Dockerfile-nginx

 container_name: teste-nginx
 ports:
  - 8000:80
 links:
  - php
 volumes:
  - .:/app
# PHP
php:
 build: .
 dockerfile: Dockerfile-php

# image: php:7.0.8-fpm-alpine
 container_name: teste-php
 volumes:
  - .:/app
